apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: efact

bases:
  - ../../base

commonLabels:
  environment: production

patches:
  - target:
      kind: Deployment
      name: ms1-documents
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3

  - target:
      kind: Deployment
      name: ms2-validator
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3

  - target:
      kind: StatefulSet
      name: elasticsearch
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3

configMapGenerator:
  - name: efact-config
    behavior: merge
    literals:
      - LOG_LEVEL=info
      - ENVIRONMENT=production
