apiVersion: v1
kind: ConfigMap
metadata:
  name: efact-config
  namespace: efact
data:
  # MongoDB Configuration
  MONGO_INITDB_DATABASE: "efact_db"
  MONGO_HOST: "mongodb-service"
  MONGO_PORT: "27017"

  # RabbitMQ Configuration
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_QUEUE: "documents.created"

  # Vault Configuration
  VAULT_ADDR: "http://vault-service:8200"

  # Elasticsearch Configuration
  ELASTICSEARCH_URL: "http://elasticsearch-service:9200"
  ES_JAVA_OPTS: "-Xms512m -Xmx512m"

  # MS1 Configuration
  MS1_PORT: "5000"

  # MS2 Configuration
  SPRING_PROFILES_ACTIVE: "prod"
