apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: efact

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - mongodb-statefulset.yaml
  - rabbitmq-statefulset.yaml
  - elasticsearch-statefulset.yaml
  - kibana-deployment.yaml
  - vault-deployment.yaml
  - ms1-deployment.yaml
  - ms2-deployment.yaml
  - ingress.yaml

commonLabels:
  project: efact
  managed-by: kustomize
