apiVersion: v1
kind: Secret
metadata:
  name: efact-secrets
  namespace: efact
type: Opaque
stringData:
  # MongoDB Credentials
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "admin123"

  # RabbitMQ Credentials
  RABBITMQ_DEFAULT_USER: "admin"
  RABBITMQ_DEFAULT_PASS: "admin123"

  # Vault Token
  VAULT_DEV_ROOT_TOKEN_ID: "efact-root-token-dev-only"
  VAULT_TOKEN: "efact-root-token-dev-only"

  # Connection Strings
  MONGO_URI: "mongodb://admin:admin123@mongodb-service:27017"
  MONGO_DB_AUTH: "mongodb://admin:admin123@mongodb-service:27017/efact_db?authSource=admin"
  RABBITMQ_URI: "amqp://admin:admin123@rabbitmq-service:5672/"
